### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by addisoncrump** [DennisMitchell/jelly#1]
Plz halp err 404 doc no fund.

**Comment by phase** [comment]
gives me docs plz

**Comment by ararslan** [comment]
I was able to reproduce the issue on my system, Mac OS X 10.10.

**Comment by phase** [comment]
@ararslan This issue has been appearing on a variety of operating system, I can confirm appearance on Windows XP. This seems to be caused by https://github.com/DennisMitchell/jelly/commit/935b138a1f544e48cb27c01396a803ec54dc7ef5, or it has been there since then.

**Comment by elendiastarman** [comment]
Likewise, Windows 10, Chrome 46, no docs found.

**Comment by lynn** [comment]
[Resolved lol](https://github.com/DennisMitchell/jelly/wiki)
