### ISSUE TITLE
Print z as a char

### ISSUE THREAD

**Issue by s5bug** [DennisMitchell/jelly#20]
If `z = 99` print `c`, if `z = 10` print a new line.

**Comment by DennisMitchell** [comment]
Apologies, but I'm not sure if this support question or a feature request.

If it is the former, you can print an integer as a character with `ỌȮ`, or just `Ọ` at the end of the program (output is implicit).

If it is the latter, I'm not sure how useful it would be; `Ȯ` is rarely useful to begin with. Do you have a specific example where this would save any bytes?

**Comment by s5bug** [comment]
Yes, sorry, the error was that I wasn't casting back to an int to increment 😫
