### ISSUE TITLE
Default ® to 250.

### ISSUE THREAD

**Issue by jared-hughes** [DennisMitchell/jelly#35]
Initializing the register `®` to 0 does not save bytes compared to `0`. Initializing the register to `250` would save 2 bytes. The number 250 is certainly useful, such as encoding lists of shorts using  `“<encoding>’b250`.

**Comment by Adriandmen** [comment]
Doesn't `“<encoding>‘‘` achieve the same effect, without the constant?

**Comment by jared-hughes** [comment]
Ah, yes. I forgot about that. Closing.
