### ISSUE TITLE
\n replaced by ¶, while the opposite should happen

### ISSUE THREAD

**Issue by GolfingSuccess** [DennisMitchell/jelly#38]
`¶` only works perfectly in `“...` literals, and I can see that the `convert_to_jelly` function actually replaces `\n` with `¶`. IMO, that should not happen, since `\n` is a more important character than `¶` IMO. The problem appears when using Unicode, which is what you usually use to make Jelly programs.

**Comment by DennisMitchell** [comment]
I don't think I understand. Could you give me an example?

**Comment by GolfingSuccess** [comment]
When using Unicode, both `”¶` and `⁾¶¶` don't act as expected. [Try it online!](https://tio.run/nexus/jelly#ARcA6P//4oCdwrYs4oG@wrbCtv/CosWS4bmY/w "Jelly – TIO Nexus")

**Comment by kckennylau** [comment]
What is the expected output?

**Comment by GolfingSuccess** [comment]
@kckennylau `['\n', ['\n', '\n']]` (problem only occurs with Unicode)

**Comment by GolfingSuccess** [comment]
The thing is that my old string compressor doesn't work anymore, but for a good cause :-)
