### ISSUE TITLE
Missing condition in dyadic chain tutorial

### ISSUE THREAD

**Issue by tophcodes** [DennisMitchell/jelly#4]
I have noticed that in the tutorial for _Dyadic Chains_ there's an incomplete sentence in the section _What's the starting value?_:

> [Otherwise, if the chain starts with](https://github.com/DennisMitchell/jelly/wiki/Tutorial/_compare/d795683329dc0032ebfafeb35e76b71be08c6255...7582e459431452a37c2e9ffb65393da0dc22d4f1#diff-eb3703691aed07935bf8e584cf7873c9R110)

I am not proficient enough in this language to know what this is supposed to say, so I can't fix it myself.

**Comment by lynn** [comment]
o_O

I actually forgot. I will get back to you when I remember. It _sort_ of looks like just a scrapped line that you can just ignore, but I can't check right now.

**Comment by CatsAreFluffy** [comment]
Maybe if it starts with a nilad, start with the nilad?

**Comment by tophcodes** [comment]
Likely not, because it wouldn't be a dyadic chain to start with. It'd be covered by the "Niladic chains" section.

**Comment by lynn** [comment]
Okay, I fixed it. Dyadic chains can start with a leading constant! And indeed, the sentence was supposed to say that, if they do, you use that one and throw away the left argument initially.
