### ISSUE TITLE
Codepage not linked anywhere

### ISSUE THREAD

**Issue by CatsAreFluffy** [DennisMitchell/jelly#5]
Pretty simple. I had to find a link on codegolf to get to it.

**Comment by DennisMitchell** [comment]
It's in the folder called _docs_.

**Comment by CatsAreFluffy** [comment]
I know. But it should be linked on the wiki homepage.

**Comment by DennisMitchell** [comment]
I actually moved it to the wiki a few minutes ago. It's now linked in the wiki's side bar and the main README.
