### ISSUE TITLE
Wrong result type for ŒG

### ISSUE THREAD

**Issue by jacobly0** [DennisMitchell/jelly#84]
ŒG seems to return a python string instead of a jellified python string (array of length 1 strings), and I can't even figure out a reasonable way to work around it because everything I've tried calls iterable which turns the string into a wrapped string.

**Comment by DennisMitchell** [comment]
Thank you for catching this.

Most calls on Python strings won't work as expected; they break too many things internally.

An easy way to convert a Python string into a Jelly string is `ṾḊ`, which turns the Python string `abc` into the Jelly string `”abc` (which doesn't make any sense), then chops off the first character.
